//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WizardWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Content { get; set; }
        public string Mood { get; set; }
        public int SessionTime { get; set; }
        public System.DateTime DateTime { get; set; }
        public int Identity { get; set; }
    }
}
